import dotenv from "dotenv";
dotenv.config();

import { Client } from "@notionhq/client";

const notion = new Client({
  auth: process.env.NOTION_API_KEY,
});

function richText(content) {
  return [
    {
      type: "text",
      text: {
        content: String(content ?? ""),
      },
    },
  ];
}

function headingBlock(text) {
  return {
    object: "block",
    type: "heading_2",
    heading_2: {
      rich_text: richText(text),
    },
  };
}

function paragraphBlock(text) {
  return {
    object: "block",
    type: "paragraph",
    paragraph: {
      rich_text: richText(text),
    },
  };
}

function bulletedListItemBlock(text) {
  return {
    object: "block",
    type: "bulleted_list_item",
    bulleted_list_item: {
      rich_text: richText(text),
    },
  };
}

function todoBlock(text, checked = false) {
  return {
    object: "block",
    type: "to_do",
    to_do: {
      rich_text: richText(text),
      checked,
    },
  };
}

export async function createNotionWorkspace({ brief, selectedDirection }) {
  const title =
    `${brief?.brandName || "Untitled Brand"} – ${selectedDirection?.title || "Selected Direction"}`;

  const page = await notion.pages.create({
    parent: {
      type: "page_id",
      page_id: process.env.NOTION_PARENT_PAGE_ID,
    },
    properties: {
      title: {
        title: richText(title),
      },
    },
    children: [
      headingBlock("Project Overview"),
      paragraphBlock(
        `Workspace generated by Merch OS for ${brief?.brandName || "the client project"}.`
      ),

      headingBlock("Client Brief"),
      bulletedListItemBlock(`Brand Name: ${brief?.brandName || ""}`),
      bulletedListItemBlock(`Audience: ${brief?.audience || ""}`),
      bulletedListItemBlock(
        `Brand Values: ${(brief?.brandValues || []).join(", ")}`
      ),
      bulletedListItemBlock(
        `Style Preferences: ${(brief?.stylePreferences || []).join(", ")}`
      ),
      bulletedListItemBlock(
        `Colour Preferences: ${(brief?.colourPreferences || []).join(", ")}`
      ),
      bulletedListItemBlock(
        `Garment Types: ${(brief?.garmentTypes || []).join(", ")}`
      ),
      paragraphBlock(`Design Notes: ${brief?.designNotes || ""}`),

      headingBlock("Selected Direction"),
      bulletedListItemBlock(`Title: ${selectedDirection?.title || ""}`),
      bulletedListItemBlock(`Hook: ${selectedDirection?.hook || ""}`),
      paragraphBlock(`Concept: ${selectedDirection?.concept || ""}`),
      bulletedListItemBlock(`Visual Style: ${selectedDirection?.visualStyle || ""}`),
      bulletedListItemBlock(`Typography: ${selectedDirection?.typography || ""}`),
      bulletedListItemBlock(
        `Colour Palette: ${(selectedDirection?.colourPalette || []).join(", ")}`
      ),
      bulletedListItemBlock(
        `Graphic Elements: ${(selectedDirection?.graphicElements || []).join(", ")}`
      ),
      paragraphBlock(`Front Design: ${selectedDirection?.frontDesign || ""}`),
      paragraphBlock(`Back Design: ${selectedDirection?.backDesign || ""}`),
      paragraphBlock(`Placement Notes: ${selectedDirection?.placementNotes || ""}`),
      bulletedListItemBlock(`Print Style: ${selectedDirection?.printStyle || ""}`),
      bulletedListItemBlock(`Reference Vibe: ${selectedDirection?.referenceVibe || ""}`),
      paragraphBlock(`Rationale: ${selectedDirection?.rationale || ""}`),

      headingBlock("Execution Checklist"),
      todoBlock("Create print-ready front graphic"),
      todoBlock("Create print-ready back graphic"),
      todoBlock("Prepare garment mockups"),
      todoBlock("Review typography and spacing"),
      todoBlock("Approve colour palette"),
      todoBlock("Export final assets"),
      todoBlock("Prepare client presentation deck"),
    ],
  });

  return {
    pageId: page.id,
    url: page.url,
    title,
  };
}