import { createNotionMcpClient } from "./notionMcpClient.js";
import {
    createProductionTasksDatabase,
    seedProductionTasks,
    createMilestonesDatabase,
    seedMilestones,
} from "./notionService.js";

function richText(content) {
    return [
        {
            type: "text",
            text: {
                content: String(content ?? ""),
            },
        },
    ];
}

function headingBlock(text) {
    return {
        object: "block",
        type: "heading_2",
        heading_2: {
            rich_text: richText(text),
        },
    };
}

function paragraphBlock(text) {
    return {
        object: "block",
        type: "paragraph",
        paragraph: {
            rich_text: richText(text),
        },
    };
}

function bulletedListItemBlock(text) {
    return {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
            rich_text: richText(text),
        },
    };
}

function briefBlocks(brief) {
    return [
        headingBlock("Client Brief"),
        bulletedListItemBlock(`Brand Name: ${brief?.brandName || ""}`),
        bulletedListItemBlock(`Audience: ${brief?.audience || ""}`),
        bulletedListItemBlock(
            `Brand Values: ${(brief?.brandValues || []).join(", ")}`
        ),
        bulletedListItemBlock(
            `Style Preferences: ${(brief?.stylePreferences || []).join(", ")}`
        ),
        bulletedListItemBlock(
            `Colour Preferences: ${(brief?.colourPreferences || []).join(", ")}`
        ),
        bulletedListItemBlock(
            `Garment Types: ${(brief?.garmentTypes || []).join(", ")}`
        ),
        paragraphBlock(`Design Notes: ${brief?.designNotes || ""}`),
    ];
}

function directionBlocks(selectedDirection) {
    return [
        headingBlock("Selected Direction"),
        bulletedListItemBlock(`Title: ${selectedDirection?.title || ""}`),
        bulletedListItemBlock(`Hook: ${selectedDirection?.hook || ""}`),
        paragraphBlock(`Concept: ${selectedDirection?.concept || ""}`),
        bulletedListItemBlock(
            `Visual Style: ${selectedDirection?.visualStyle || ""}`
        ),
        bulletedListItemBlock(`Typography: ${selectedDirection?.typography || ""}`),
        bulletedListItemBlock(
            `Colour Palette: ${(selectedDirection?.colourPalette || []).join(", ")}`
        ),
        bulletedListItemBlock(
            `Graphic Elements: ${(selectedDirection?.graphicElements || []).join(", ")}`
        ),
        paragraphBlock(`Front Design: ${selectedDirection?.frontDesign || ""}`),
        paragraphBlock(`Back Design: ${selectedDirection?.backDesign || ""}`),
        paragraphBlock(
            `Placement Notes: ${selectedDirection?.placementNotes || ""}`
        ),
        bulletedListItemBlock(`Print Style: ${selectedDirection?.printStyle || ""}`),
        bulletedListItemBlock(
            `Reference Vibe: ${selectedDirection?.referenceVibe || ""}`
        ),
        paragraphBlock(`Rationale: ${selectedDirection?.rationale || ""}`),
    ];
}

function extractJson(toolResult) {
    const text = toolResult?.content?.find((item) => item.type === "text")?.text;
    if (!text) {
        throw new Error("MCP tool returned no text content.");
    }
    return JSON.parse(text);
}

async function callTool(client, name, args) {
    const result = await client.callTool({
        name,
        arguments: args,
    });
    return extractJson(result);
}

export async function createNotionWorkspaceViaMcp({ brief, selectedDirection }) {
    const client = await createNotionMcpClient();
    const workspaceTitle = `${brief?.brandName || "Untitled Brand"} – Merch Workspace`;

    const parentPage = await callTool(client, "API-post-page", {
        parent: {
            type: "page_id",
            page_id: process.env.NOTION_PARENT_PAGE_ID,
        },
        properties: {
            title: {
                title: richText(workspaceTitle),
            },
        },
        children: [
            headingBlock("Workspace Overview"),
            paragraphBlock(
                `Workspace generated by Merch OS for ${brief?.brandName || "the client project"}.`
            ),
        ],
    });

    await callTool(client, "API-post-page", {
        parent: {
            type: "page_id",
            page_id: parentPage.id,
        },
        properties: {
            title: {
                title: richText("Brand Brief"),
            },
        },
        children: briefBlocks(brief),
    });

    await callTool(client, "API-post-page", {
        parent: {
            type: "page_id",
            page_id: parentPage.id,
        },
        properties: {
            title: {
                title: richText("Design Directions"),
            },
        },
        children: directionBlocks(selectedDirection),
    });

    await callTool(client, "API-post-page", {
        parent: {
            type: "page_id",
            page_id: parentPage.id,
        },
        properties: {
            title: {
                title: richText("Feedback"),
            },
        },
        children: [
            headingBlock("Client Feedback"),
            paragraphBlock("Log client notes and approvals here."),
            headingBlock("Internal Feedback"),
            paragraphBlock("Track internal reviews and QA notes here."),
        ],
    });

    const productionDb = await createProductionTasksDatabase(parentPage.id);
    await seedProductionTasks(productionDb.dataSourceId, selectedDirection, brief);

    const milestonesDb = await createMilestonesDatabase(parentPage.id);
    await seedMilestones(milestonesDb.dataSourceId, brief);

    return {
        pageId: parentPage.id,
        url: parentPage.url,
        title: workspaceTitle,
        productionDatabaseUrl: productionDb.url,
        milestonesDatabaseUrl: milestonesDb.url,
    };
}