import dotenv from "dotenv";
dotenv.config();

import { Client } from "@notionhq/client";

const notion = new Client({
  auth: process.env.NOTION_API_KEY,
});

const TASK_DB_FIELDS = {
  NAME: "Name",
  STATUS: "Status",
  CATEGORY: "Category",
  PRIORITY: "Priority",
  DIRECTION: "Direction",
};

function richText(content) {
  return [
    {
      type: "text",
      text: {
        content: String(content ?? ""),
      },
    },
  ];
}

function productionDatabaseProperties() {
  return {
    [TASK_DB_FIELDS.NAME]: {
      title: {},
    },
    [TASK_DB_FIELDS.STATUS]: {
      select: {
        options: [
          { name: "Not Started", color: "default" },
          { name: "In Progress", color: "yellow" },
          { name: "Done", color: "green" },
        ],
      },
    },
    [TASK_DB_FIELDS.CATEGORY]: {
      select: {
        options: [
          { name: "Design", color: "blue" },
          { name: "Review", color: "purple" },
          { name: "Production", color: "orange" },
        ],
      },
    },
    [TASK_DB_FIELDS.PRIORITY]: {
      select: {
        options: [
          { name: "Low", color: "gray" },
          { name: "Medium", color: "brown" },
          { name: "High", color: "red" },
        ],
      },
    },
    [TASK_DB_FIELDS.DIRECTION]: {
      rich_text: {},
    },
  };
}

function getDataSourceId(databaseResponse) {
  return (
    databaseResponse?.initial_data_source?.id ||
    databaseResponse?.data_sources?.[0]?.id ||
    null
  );
}

export async function createProductionTasksDatabase(parentPageId) {
  const productionTasksDatabase = await notion.databases.create({
    parent: {
      type: "page_id",
      page_id: parentPageId,
    },
    title: richText("Production Tasks"),
    is_inline: true,
    initial_data_source: {
      properties: productionDatabaseProperties(),
    },
  });

  const dataSourceId = getDataSourceId(productionTasksDatabase);

  if (!dataSourceId) {
    throw new Error(
      "Production Tasks database was created, but no data source ID was returned."
    );
  }

  return {
    databaseId: productionTasksDatabase.id,
    dataSourceId,
    url: productionTasksDatabase.url,
  };
}

export async function seedProductionTasks(dataSourceId, selectedDirection) {
  const starterTasks = [
    { name: "Create front graphic", category: "Design", priority: "High" },
    { name: "Create back graphic", category: "Design", priority: "High" },
    {
      name: "Prepare garment mockups",
      category: "Production",
      priority: "Medium",
    },
    {
      name: "Review client feedback",
      category: "Review",
      priority: "Medium",
    },
  ];

  for (const task of starterTasks) {
    await notion.pages.create({
      parent: {
        type: "data_source_id",
        data_source_id: dataSourceId,
      },
      properties: {
        [TASK_DB_FIELDS.NAME]: {
          title: richText(task.name),
        },
        [TASK_DB_FIELDS.STATUS]: {
          select: {
            name: "Not Started",
          },
        },
        [TASK_DB_FIELDS.CATEGORY]: {
          select: {
            name: task.category,
          },
        },
        [TASK_DB_FIELDS.PRIORITY]: {
          select: {
            name: task.priority,
          },
        },
        [TASK_DB_FIELDS.DIRECTION]: {
          rich_text: richText(
            selectedDirection?.title || "Selected Direction"
          ),
        },
      },
    });
  }
}

export async function createNotionWorkspace({ brief, selectedDirection }) {
  const workspaceTitle = `${brief?.brandName || "Untitled Brand"
    } – Merch Workspace`;

  const parentPage = await notion.pages.create({
    parent: {
      type: "page_id",
      page_id: process.env.NOTION_PARENT_PAGE_ID,
    },
    properties: {
      title: {
        title: richText(workspaceTitle),
      },
    },
    children: [
      {
        object: "block",
        type: "heading_2",
        heading_2: {
          rich_text: richText("Workspace Overview"),
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: richText(
            `Workspace generated by Merch OS for ${brief?.brandName || "the client project"
            }.`
          ),
        },
      },
    ],
  });

  await notion.pages.create({
    parent: {
      type: "page_id",
      page_id: parentPage.id,
    },
    properties: {
      title: {
        title: richText("Brand Brief"),
      },
    },
    children: [
      {
        object: "block",
        type: "heading_2",
        heading_2: {
          rich_text: richText("Client Brief"),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(`Brand Name: ${brief?.brandName || ""}`),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(`Audience: ${brief?.audience || ""}`),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(
            `Brand Values: ${(brief?.brandValues || []).join(", ")}`
          ),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(
            `Style Preferences: ${(brief?.stylePreferences || []).join(", ")}`
          ),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(
            `Colour Preferences: ${(brief?.colourPreferences || []).join(", ")}`
          ),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(
            `Garment Types: ${(brief?.garmentTypes || []).join(", ")}`
          ),
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: richText(`Design Notes: ${brief?.designNotes || ""}`),
        },
      },
    ],
  });

  await notion.pages.create({
    parent: {
      type: "page_id",
      page_id: parentPage.id,
    },
    properties: {
      title: {
        title: richText("Design Directions"),
      },
    },
    children: [
      {
        object: "block",
        type: "heading_2",
        heading_2: {
          rich_text: richText("Selected Direction"),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(`Title: ${selectedDirection?.title || ""}`),
        },
      },
      {
        object: "block",
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: richText(`Hook: ${selectedDirection?.hook || ""}`),
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: richText(`Concept: ${selectedDirection?.concept || ""}`),
        },
      },
    ],
  });

  await notion.pages.create({
    parent: {
      type: "page_id",
      page_id: parentPage.id,
    },
    properties: {
      title: {
        title: richText("Feedback"),
      },
    },
    children: [
      {
        object: "block",
        type: "heading_2",
        heading_2: {
          rich_text: richText("Client Feedback"),
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: richText("Log client notes and approvals here."),
        },
      },
      {
        object: "block",
        type: "heading_2",
        heading_2: {
          rich_text: richText("Internal Feedback"),
        },
      },
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: richText("Track internal reviews and QA notes here."),
        },
      },
    ],
  });

  const productionDb = await createProductionTasksDatabase(parentPage.id);
  await seedProductionTasks(productionDb.dataSourceId, selectedDirection);

  return {
    pageId: parentPage.id,
    url: parentPage.url,
    title: workspaceTitle,
    productionDatabaseUrl: productionDb.url,
  };
}